package roach

opaque type SQLSTATE = String
object SQLSTATE:
  extension (inline v: SQLSTATE) transparent inline def code = inlineCode(v)
  inline def successful_completion: SQLSTATE = "successful_completion"
  inline def warning: SQLSTATE = "warning"
  inline def dynamic_result_sets_returned: SQLSTATE =
    "dynamic_result_sets_returned"
  inline def implicit_zero_bit_padding: SQLSTATE = "implicit_zero_bit_padding"
  inline def null_value_eliminated_in_set_function: SQLSTATE =
    "null_value_eliminated_in_set_function"
  inline def privilege_not_granted: SQLSTATE = "privilege_not_granted"
  inline def privilege_not_revoked: SQLSTATE = "privilege_not_revoked"
  inline def string_data_right_truncation: SQLSTATE =
    "string_data_right_truncation"
  inline def deprecated_feature: SQLSTATE = "deprecated_feature"
  inline def no_data: SQLSTATE = "no_data"
  inline def no_additional_dynamic_result_sets_returned: SQLSTATE =
    "no_additional_dynamic_result_sets_returned"
  inline def sql_statement_not_yet_complete: SQLSTATE =
    "sql_statement_not_yet_complete"
  inline def connection_exception: SQLSTATE = "connection_exception"
  inline def connection_does_not_exist: SQLSTATE = "connection_does_not_exist"
  inline def connection_failure: SQLSTATE = "connection_failure"
  inline def sqlclient_unable_to_establish_sqlconnection: SQLSTATE =
    "sqlclient_unable_to_establish_sqlconnection"
  inline def sqlserver_rejected_establishment_of_sqlconnection: SQLSTATE =
    "sqlserver_rejected_establishment_of_sqlconnection"
  inline def transaction_resolution_unknown: SQLSTATE =
    "transaction_resolution_unknown"
  inline def protocol_violation: SQLSTATE = "protocol_violation"
  inline def triggered_action_exception: SQLSTATE = "triggered_action_exception"
  inline def feature_not_supported: SQLSTATE = "feature_not_supported"
  inline def invalid_transaction_initiation: SQLSTATE =
    "invalid_transaction_initiation"
  inline def locator_exception: SQLSTATE = "locator_exception"
  inline def invalid_locator_specification: SQLSTATE =
    "invalid_locator_specification"
  inline def invalid_grantor: SQLSTATE = "invalid_grantor"
  inline def invalid_grant_operation: SQLSTATE = "invalid_grant_operation"
  inline def invalid_role_specification: SQLSTATE = "invalid_role_specification"
  inline def diagnostics_exception: SQLSTATE = "diagnostics_exception"
  inline def stacked_diagnostics_accessed_without_active_handler: SQLSTATE =
    "stacked_diagnostics_accessed_without_active_handler"
  inline def case_not_found: SQLSTATE = "case_not_found"
  inline def cardinality_violation: SQLSTATE = "cardinality_violation"
  inline def data_exception: SQLSTATE = "data_exception"
  inline def array_subscript_error: SQLSTATE = "array_subscript_error"
  inline def character_not_in_repertoire: SQLSTATE =
    "character_not_in_repertoire"
  inline def datetime_field_overflow: SQLSTATE = "datetime_field_overflow"
  inline def division_by_zero: SQLSTATE = "division_by_zero"
  inline def error_in_assignment: SQLSTATE = "error_in_assignment"
  inline def escape_character_conflict: SQLSTATE = "escape_character_conflict"
  inline def indicator_overflow: SQLSTATE = "indicator_overflow"
  inline def interval_field_overflow: SQLSTATE = "interval_field_overflow"
  inline def invalid_argument_for_logarithm: SQLSTATE =
    "invalid_argument_for_logarithm"
  inline def invalid_argument_for_ntile_function: SQLSTATE =
    "invalid_argument_for_ntile_function"
  inline def invalid_argument_for_nth_value_function: SQLSTATE =
    "invalid_argument_for_nth_value_function"
  inline def invalid_argument_for_power_function: SQLSTATE =
    "invalid_argument_for_power_function"
  inline def invalid_argument_for_width_bucket_function: SQLSTATE =
    "invalid_argument_for_width_bucket_function"
  inline def invalid_character_value_for_cast: SQLSTATE =
    "invalid_character_value_for_cast"
  inline def invalid_datetime_format: SQLSTATE = "invalid_datetime_format"
  inline def invalid_escape_character: SQLSTATE = "invalid_escape_character"
  inline def invalid_escape_octet: SQLSTATE = "invalid_escape_octet"
  inline def invalid_escape_sequence: SQLSTATE = "invalid_escape_sequence"
  inline def nonstandard_use_of_escape_character: SQLSTATE =
    "nonstandard_use_of_escape_character"
  inline def invalid_indicator_parameter_value: SQLSTATE =
    "invalid_indicator_parameter_value"
  inline def invalid_parameter_value: SQLSTATE = "invalid_parameter_value"
  inline def invalid_preceding_or_following_size: SQLSTATE =
    "invalid_preceding_or_following_size"
  inline def invalid_regular_expression: SQLSTATE = "invalid_regular_expression"
  inline def invalid_row_count_in_limit_clause: SQLSTATE =
    "invalid_row_count_in_limit_clause"
  inline def invalid_row_count_in_result_offset_clause: SQLSTATE =
    "invalid_row_count_in_result_offset_clause"
  inline def invalid_tablesample_argument: SQLSTATE =
    "invalid_tablesample_argument"
  inline def invalid_tablesample_repeat: SQLSTATE = "invalid_tablesample_repeat"
  inline def invalid_time_zone_displacement_value: SQLSTATE =
    "invalid_time_zone_displacement_value"
  inline def invalid_use_of_escape_character: SQLSTATE =
    "invalid_use_of_escape_character"
  inline def most_specific_type_mismatch: SQLSTATE =
    "most_specific_type_mismatch"
  inline def null_value_not_allowed: SQLSTATE = "null_value_not_allowed"
  inline def null_value_no_indicator_parameter: SQLSTATE =
    "null_value_no_indicator_parameter"
  inline def numeric_value_out_of_range: SQLSTATE = "numeric_value_out_of_range"
  inline def sequence_generator_limit_exceeded: SQLSTATE =
    "sequence_generator_limit_exceeded"
  inline def string_data_length_mismatch: SQLSTATE =
    "string_data_length_mismatch"
  inline def substring_error: SQLSTATE = "substring_error"
  inline def trim_error: SQLSTATE = "trim_error"
  inline def unterminated_c_string: SQLSTATE = "unterminated_c_string"
  inline def zero_length_character_string: SQLSTATE =
    "zero_length_character_string"
  inline def floating_point_exception: SQLSTATE = "floating_point_exception"
  inline def invalid_text_representation: SQLSTATE =
    "invalid_text_representation"
  inline def invalid_binary_representation: SQLSTATE =
    "invalid_binary_representation"
  inline def bad_copy_file_format: SQLSTATE = "bad_copy_file_format"
  inline def untranslatable_character: SQLSTATE = "untranslatable_character"
  inline def not_an_xml_document: SQLSTATE = "not_an_xml_document"
  inline def invalid_xml_document: SQLSTATE = "invalid_xml_document"
  inline def invalid_xml_content: SQLSTATE = "invalid_xml_content"
  inline def invalid_xml_comment: SQLSTATE = "invalid_xml_comment"
  inline def invalid_xml_processing_instruction: SQLSTATE =
    "invalid_xml_processing_instruction"
  inline def duplicate_json_object_key_value: SQLSTATE =
    "duplicate_json_object_key_value"
  inline def invalid_argument_for_sql_json_datetime_function: SQLSTATE =
    "invalid_argument_for_sql_json_datetime_function"
  inline def invalid_json_text: SQLSTATE = "invalid_json_text"
  inline def invalid_sql_json_subscript: SQLSTATE = "invalid_sql_json_subscript"
  inline def more_than_one_sql_json_item: SQLSTATE =
    "more_than_one_sql_json_item"
  inline def no_sql_json_item: SQLSTATE = "no_sql_json_item"
  inline def non_numeric_sql_json_item: SQLSTATE = "non_numeric_sql_json_item"
  inline def non_unique_keys_in_a_json_object: SQLSTATE =
    "non_unique_keys_in_a_json_object"
  inline def singleton_sql_json_item_required: SQLSTATE =
    "singleton_sql_json_item_required"
  inline def sql_json_array_not_found: SQLSTATE = "sql_json_array_not_found"
  inline def sql_json_member_not_found: SQLSTATE = "sql_json_member_not_found"
  inline def sql_json_number_not_found: SQLSTATE = "sql_json_number_not_found"
  inline def sql_json_object_not_found: SQLSTATE = "sql_json_object_not_found"
  inline def too_many_json_array_elements: SQLSTATE =
    "too_many_json_array_elements"
  inline def too_many_json_object_members: SQLSTATE =
    "too_many_json_object_members"
  inline def sql_json_scalar_required: SQLSTATE = "sql_json_scalar_required"
  inline def sql_json_item_cannot_be_cast_to_target_type: SQLSTATE =
    "sql_json_item_cannot_be_cast_to_target_type"
  inline def integrity_constraint_violation: SQLSTATE =
    "integrity_constraint_violation"
  inline def restrict_violation: SQLSTATE = "restrict_violation"
  inline def not_null_violation: SQLSTATE = "not_null_violation"
  inline def foreign_key_violation: SQLSTATE = "foreign_key_violation"
  inline def unique_violation: SQLSTATE = "unique_violation"
  inline def check_violation: SQLSTATE = "check_violation"
  inline def exclusion_violation: SQLSTATE = "exclusion_violation"
  inline def invalid_cursor_state: SQLSTATE = "invalid_cursor_state"
  inline def invalid_transaction_state: SQLSTATE = "invalid_transaction_state"
  inline def active_sql_transaction: SQLSTATE = "active_sql_transaction"
  inline def branch_transaction_already_active: SQLSTATE =
    "branch_transaction_already_active"
  inline def held_cursor_requires_same_isolation_level: SQLSTATE =
    "held_cursor_requires_same_isolation_level"
  inline def inappropriate_access_mode_for_branch_transaction: SQLSTATE =
    "inappropriate_access_mode_for_branch_transaction"
  inline def inappropriate_isolation_level_for_branch_transaction: SQLSTATE =
    "inappropriate_isolation_level_for_branch_transaction"
  inline def no_active_sql_transaction_for_branch_transaction: SQLSTATE =
    "no_active_sql_transaction_for_branch_transaction"
  inline def read_only_sql_transaction: SQLSTATE = "read_only_sql_transaction"
  inline def schema_and_data_statement_mixing_not_supported: SQLSTATE =
    "schema_and_data_statement_mixing_not_supported"
  inline def no_active_sql_transaction: SQLSTATE = "no_active_sql_transaction"
  inline def in_failed_sql_transaction: SQLSTATE = "in_failed_sql_transaction"
  inline def idle_in_transaction_session_timeout: SQLSTATE =
    "idle_in_transaction_session_timeout"
  inline def invalid_sql_statement_name: SQLSTATE = "invalid_sql_statement_name"
  inline def triggered_data_change_violation: SQLSTATE =
    "triggered_data_change_violation"
  inline def invalid_authorization_specification: SQLSTATE =
    "invalid_authorization_specification"
  inline def invalid_password: SQLSTATE = "invalid_password"
  inline def dependent_privilege_descriptors_still_exist: SQLSTATE =
    "dependent_privilege_descriptors_still_exist"
  inline def dependent_objects_still_exist: SQLSTATE =
    "dependent_objects_still_exist"
  inline def invalid_transaction_termination: SQLSTATE =
    "invalid_transaction_termination"
  inline def sql_routine_exception: SQLSTATE = "sql_routine_exception"
  inline def function_executed_no_return_statement: SQLSTATE =
    "function_executed_no_return_statement"
  inline def modifying_sql_data_not_permitted: SQLSTATE =
    "modifying_sql_data_not_permitted"
  inline def prohibited_sql_statement_attempted: SQLSTATE =
    "prohibited_sql_statement_attempted"
  inline def reading_sql_data_not_permitted: SQLSTATE =
    "reading_sql_data_not_permitted"
  inline def invalid_cursor_name: SQLSTATE = "invalid_cursor_name"
  inline def external_routine_exception: SQLSTATE = "external_routine_exception"
  inline def containing_sql_not_permitted: SQLSTATE =
    "containing_sql_not_permitted"
  inline def external_routine_invocation_exception: SQLSTATE =
    "external_routine_invocation_exception"
  inline def invalid_sqlstate_returned: SQLSTATE = "invalid_sqlstate_returned"
  inline def trigger_protocol_violated: SQLSTATE = "trigger_protocol_violated"
  inline def srf_protocol_violated: SQLSTATE = "srf_protocol_violated"
  inline def event_trigger_protocol_violated: SQLSTATE =
    "event_trigger_protocol_violated"
  inline def savepoint_exception: SQLSTATE = "savepoint_exception"
  inline def invalid_savepoint_specification: SQLSTATE =
    "invalid_savepoint_specification"
  inline def invalid_catalog_name: SQLSTATE = "invalid_catalog_name"
  inline def invalid_schema_name: SQLSTATE = "invalid_schema_name"
  inline def transaction_rollback: SQLSTATE = "transaction_rollback"
  inline def transaction_integrity_constraint_violation: SQLSTATE =
    "transaction_integrity_constraint_violation"
  inline def serialization_failure: SQLSTATE = "serialization_failure"
  inline def statement_completion_unknown: SQLSTATE =
    "statement_completion_unknown"
  inline def deadlock_detected: SQLSTATE = "deadlock_detected"
  inline def syntax_error_or_access_rule_violation: SQLSTATE =
    "syntax_error_or_access_rule_violation"
  inline def syntax_error: SQLSTATE = "syntax_error"
  inline def insufficient_privilege: SQLSTATE = "insufficient_privilege"
  inline def cannot_coerce: SQLSTATE = "cannot_coerce"
  inline def grouping_error: SQLSTATE = "grouping_error"
  inline def windowing_error: SQLSTATE = "windowing_error"
  inline def invalid_recursion: SQLSTATE = "invalid_recursion"
  inline def invalid_foreign_key: SQLSTATE = "invalid_foreign_key"
  inline def invalid_name: SQLSTATE = "invalid_name"
  inline def name_too_long: SQLSTATE = "name_too_long"
  inline def reserved_name: SQLSTATE = "reserved_name"
  inline def datatype_mismatch: SQLSTATE = "datatype_mismatch"
  inline def indeterminate_datatype: SQLSTATE = "indeterminate_datatype"
  inline def collation_mismatch: SQLSTATE = "collation_mismatch"
  inline def indeterminate_collation: SQLSTATE = "indeterminate_collation"
  inline def wrong_object_type: SQLSTATE = "wrong_object_type"
  inline def generated_always: SQLSTATE = "generated_always"
  inline def undefined_column: SQLSTATE = "undefined_column"
  inline def undefined_function: SQLSTATE = "undefined_function"
  inline def undefined_table: SQLSTATE = "undefined_table"
  inline def undefined_parameter: SQLSTATE = "undefined_parameter"
  inline def undefined_object: SQLSTATE = "undefined_object"
  inline def duplicate_column: SQLSTATE = "duplicate_column"
  inline def duplicate_cursor: SQLSTATE = "duplicate_cursor"
  inline def duplicate_database: SQLSTATE = "duplicate_database"
  inline def duplicate_function: SQLSTATE = "duplicate_function"
  inline def duplicate_prepared_statement: SQLSTATE =
    "duplicate_prepared_statement"
  inline def duplicate_schema: SQLSTATE = "duplicate_schema"
  inline def duplicate_table: SQLSTATE = "duplicate_table"
  inline def duplicate_alias: SQLSTATE = "duplicate_alias"
  inline def duplicate_object: SQLSTATE = "duplicate_object"
  inline def ambiguous_column: SQLSTATE = "ambiguous_column"
  inline def ambiguous_function: SQLSTATE = "ambiguous_function"
  inline def ambiguous_parameter: SQLSTATE = "ambiguous_parameter"
  inline def ambiguous_alias: SQLSTATE = "ambiguous_alias"
  inline def invalid_column_reference: SQLSTATE = "invalid_column_reference"
  inline def invalid_column_definition: SQLSTATE = "invalid_column_definition"
  inline def invalid_cursor_definition: SQLSTATE = "invalid_cursor_definition"
  inline def invalid_database_definition: SQLSTATE =
    "invalid_database_definition"
  inline def invalid_function_definition: SQLSTATE =
    "invalid_function_definition"
  inline def invalid_prepared_statement_definition: SQLSTATE =
    "invalid_prepared_statement_definition"
  inline def invalid_schema_definition: SQLSTATE = "invalid_schema_definition"
  inline def invalid_table_definition: SQLSTATE = "invalid_table_definition"
  inline def invalid_object_definition: SQLSTATE = "invalid_object_definition"
  inline def with_check_option_violation: SQLSTATE =
    "with_check_option_violation"
  inline def insufficient_resources: SQLSTATE = "insufficient_resources"
  inline def disk_full: SQLSTATE = "disk_full"
  inline def out_of_memory: SQLSTATE = "out_of_memory"
  inline def too_many_connections: SQLSTATE = "too_many_connections"
  inline def configuration_limit_exceeded: SQLSTATE =
    "configuration_limit_exceeded"
  inline def program_limit_exceeded: SQLSTATE = "program_limit_exceeded"
  inline def statement_too_complex: SQLSTATE = "statement_too_complex"
  inline def too_many_columns: SQLSTATE = "too_many_columns"
  inline def too_many_arguments: SQLSTATE = "too_many_arguments"
  inline def object_not_in_prerequisite_state: SQLSTATE =
    "object_not_in_prerequisite_state"
  inline def object_in_use: SQLSTATE = "object_in_use"
  inline def cant_change_runtime_param: SQLSTATE = "cant_change_runtime_param"
  inline def lock_not_available: SQLSTATE = "lock_not_available"
  inline def unsafe_new_enum_value_usage: SQLSTATE =
    "unsafe_new_enum_value_usage"
  inline def operator_intervention: SQLSTATE = "operator_intervention"
  inline def query_canceled: SQLSTATE = "query_canceled"
  inline def admin_shutdown: SQLSTATE = "admin_shutdown"
  inline def crash_shutdown: SQLSTATE = "crash_shutdown"
  inline def cannot_connect_now: SQLSTATE = "cannot_connect_now"
  inline def database_dropped: SQLSTATE = "database_dropped"
  inline def idle_session_timeout: SQLSTATE = "idle_session_timeout"
  inline def system_error: SQLSTATE = "system_error"
  inline def io_error: SQLSTATE = "io_error"
  inline def undefined_file: SQLSTATE = "undefined_file"
  inline def duplicate_file: SQLSTATE = "duplicate_file"
  inline def snapshot_too_old: SQLSTATE = "snapshot_too_old"
  inline def config_file_error: SQLSTATE = "config_file_error"
  inline def lock_file_exists: SQLSTATE = "lock_file_exists"
  inline def fdw_error: SQLSTATE = "fdw_error"
  inline def fdw_column_name_not_found: SQLSTATE = "fdw_column_name_not_found"
  inline def fdw_dynamic_parameter_value_needed: SQLSTATE =
    "fdw_dynamic_parameter_value_needed"
  inline def fdw_function_sequence_error: SQLSTATE =
    "fdw_function_sequence_error"
  inline def fdw_inconsistent_descriptor_information: SQLSTATE =
    "fdw_inconsistent_descriptor_information"
  inline def fdw_invalid_attribute_value: SQLSTATE =
    "fdw_invalid_attribute_value"
  inline def fdw_invalid_column_name: SQLSTATE = "fdw_invalid_column_name"
  inline def fdw_invalid_column_number: SQLSTATE = "fdw_invalid_column_number"
  inline def fdw_invalid_data_type: SQLSTATE = "fdw_invalid_data_type"
  inline def fdw_invalid_data_type_descriptors: SQLSTATE =
    "fdw_invalid_data_type_descriptors"
  inline def fdw_invalid_descriptor_field_identifier: SQLSTATE =
    "fdw_invalid_descriptor_field_identifier"
  inline def fdw_invalid_handle: SQLSTATE = "fdw_invalid_handle"
  inline def fdw_invalid_option_index: SQLSTATE = "fdw_invalid_option_index"
  inline def fdw_invalid_option_name: SQLSTATE = "fdw_invalid_option_name"
  inline def fdw_invalid_string_length_or_buffer_length: SQLSTATE =
    "fdw_invalid_string_length_or_buffer_length"
  inline def fdw_invalid_string_format: SQLSTATE = "fdw_invalid_string_format"
  inline def fdw_invalid_use_of_null_pointer: SQLSTATE =
    "fdw_invalid_use_of_null_pointer"
  inline def fdw_too_many_handles: SQLSTATE = "fdw_too_many_handles"
  inline def fdw_out_of_memory: SQLSTATE = "fdw_out_of_memory"
  inline def fdw_no_schemas: SQLSTATE = "fdw_no_schemas"
  inline def fdw_option_name_not_found: SQLSTATE = "fdw_option_name_not_found"
  inline def fdw_reply_handle: SQLSTATE = "fdw_reply_handle"
  inline def fdw_schema_not_found: SQLSTATE = "fdw_schema_not_found"
  inline def fdw_table_not_found: SQLSTATE = "fdw_table_not_found"
  inline def fdw_unable_to_create_execution: SQLSTATE =
    "fdw_unable_to_create_execution"
  inline def fdw_unable_to_create_reply: SQLSTATE = "fdw_unable_to_create_reply"
  inline def fdw_unable_to_establish_connection: SQLSTATE =
    "fdw_unable_to_establish_connection"
  inline def plpgsql_error: SQLSTATE = "plpgsql_error"
  inline def raise_exception: SQLSTATE = "raise_exception"
  inline def no_data_found: SQLSTATE = "no_data_found"
  inline def too_many_rows: SQLSTATE = "too_many_rows"
  inline def assert_failure: SQLSTATE = "assert_failure"
  inline def internal_error: SQLSTATE = "internal_error"
  inline def data_corrupted: SQLSTATE = "data_corrupted"
  inline def index_corrupted: SQLSTATE = "index_corrupted"

  def lookup(code: String): Option[SQLSTATE] =
    code match
      case "00000" => Some(successful_completion)
      case "01000" => Some(warning)
      case "0100C" => Some(dynamic_result_sets_returned)
      case "01008" => Some(implicit_zero_bit_padding)
      case "01003" => Some(null_value_eliminated_in_set_function)
      case "01007" => Some(privilege_not_granted)
      case "01006" => Some(privilege_not_revoked)
      case "01004" => Some(string_data_right_truncation)
      case "01P01" => Some(deprecated_feature)
      case "02000" => Some(no_data)
      case "02001" => Some(no_additional_dynamic_result_sets_returned)
      case "03000" => Some(sql_statement_not_yet_complete)
      case "08000" => Some(connection_exception)
      case "08003" => Some(connection_does_not_exist)
      case "08006" => Some(connection_failure)
      case "08001" => Some(sqlclient_unable_to_establish_sqlconnection)
      case "08004" => Some(sqlserver_rejected_establishment_of_sqlconnection)
      case "08007" => Some(transaction_resolution_unknown)
      case "08P01" => Some(protocol_violation)
      case "09000" => Some(triggered_action_exception)
      case "0A000" => Some(feature_not_supported)
      case "0B000" => Some(invalid_transaction_initiation)
      case "0F000" => Some(locator_exception)
      case "0F001" => Some(invalid_locator_specification)
      case "0L000" => Some(invalid_grantor)
      case "0LP01" => Some(invalid_grant_operation)
      case "0P000" => Some(invalid_role_specification)
      case "0Z000" => Some(diagnostics_exception)
      case "0Z002" => Some(stacked_diagnostics_accessed_without_active_handler)
      case "20000" => Some(case_not_found)
      case "21000" => Some(cardinality_violation)
      case "22000" => Some(data_exception)
      case "2202E" => Some(array_subscript_error)
      case "22021" => Some(character_not_in_repertoire)
      case "22008" => Some(datetime_field_overflow)
      case "22012" => Some(division_by_zero)
      case "22005" => Some(error_in_assignment)
      case "2200B" => Some(escape_character_conflict)
      case "22022" => Some(indicator_overflow)
      case "22015" => Some(interval_field_overflow)
      case "2201E" => Some(invalid_argument_for_logarithm)
      case "22014" => Some(invalid_argument_for_ntile_function)
      case "22016" => Some(invalid_argument_for_nth_value_function)
      case "2201F" => Some(invalid_argument_for_power_function)
      case "2201G" => Some(invalid_argument_for_width_bucket_function)
      case "22018" => Some(invalid_character_value_for_cast)
      case "22007" => Some(invalid_datetime_format)
      case "22019" => Some(invalid_escape_character)
      case "2200D" => Some(invalid_escape_octet)
      case "22025" => Some(invalid_escape_sequence)
      case "22P06" => Some(nonstandard_use_of_escape_character)
      case "22010" => Some(invalid_indicator_parameter_value)
      case "22023" => Some(invalid_parameter_value)
      case "22013" => Some(invalid_preceding_or_following_size)
      case "2201B" => Some(invalid_regular_expression)
      case "2201W" => Some(invalid_row_count_in_limit_clause)
      case "2201X" => Some(invalid_row_count_in_result_offset_clause)
      case "2202H" => Some(invalid_tablesample_argument)
      case "2202G" => Some(invalid_tablesample_repeat)
      case "22009" => Some(invalid_time_zone_displacement_value)
      case "2200C" => Some(invalid_use_of_escape_character)
      case "2200G" => Some(most_specific_type_mismatch)
      case "22004" => Some(null_value_not_allowed)
      case "22002" => Some(null_value_no_indicator_parameter)
      case "22003" => Some(numeric_value_out_of_range)
      case "2200H" => Some(sequence_generator_limit_exceeded)
      case "22026" => Some(string_data_length_mismatch)
      case "22001" => Some(string_data_right_truncation)
      case "22011" => Some(substring_error)
      case "22027" => Some(trim_error)
      case "22024" => Some(unterminated_c_string)
      case "2200F" => Some(zero_length_character_string)
      case "22P01" => Some(floating_point_exception)
      case "22P02" => Some(invalid_text_representation)
      case "22P03" => Some(invalid_binary_representation)
      case "22P04" => Some(bad_copy_file_format)
      case "22P05" => Some(untranslatable_character)
      case "2200L" => Some(not_an_xml_document)
      case "2200M" => Some(invalid_xml_document)
      case "2200N" => Some(invalid_xml_content)
      case "2200S" => Some(invalid_xml_comment)
      case "2200T" => Some(invalid_xml_processing_instruction)
      case "22030" => Some(duplicate_json_object_key_value)
      case "22031" => Some(invalid_argument_for_sql_json_datetime_function)
      case "22032" => Some(invalid_json_text)
      case "22033" => Some(invalid_sql_json_subscript)
      case "22034" => Some(more_than_one_sql_json_item)
      case "22035" => Some(no_sql_json_item)
      case "22036" => Some(non_numeric_sql_json_item)
      case "22037" => Some(non_unique_keys_in_a_json_object)
      case "22038" => Some(singleton_sql_json_item_required)
      case "22039" => Some(sql_json_array_not_found)
      case "2203A" => Some(sql_json_member_not_found)
      case "2203B" => Some(sql_json_number_not_found)
      case "2203C" => Some(sql_json_object_not_found)
      case "2203D" => Some(too_many_json_array_elements)
      case "2203E" => Some(too_many_json_object_members)
      case "2203F" => Some(sql_json_scalar_required)
      case "2203G" => Some(sql_json_item_cannot_be_cast_to_target_type)
      case "23000" => Some(integrity_constraint_violation)
      case "23001" => Some(restrict_violation)
      case "23502" => Some(not_null_violation)
      case "23503" => Some(foreign_key_violation)
      case "23505" => Some(unique_violation)
      case "23514" => Some(check_violation)
      case "23P01" => Some(exclusion_violation)
      case "24000" => Some(invalid_cursor_state)
      case "25000" => Some(invalid_transaction_state)
      case "25001" => Some(active_sql_transaction)
      case "25002" => Some(branch_transaction_already_active)
      case "25008" => Some(held_cursor_requires_same_isolation_level)
      case "25003" => Some(inappropriate_access_mode_for_branch_transaction)
      case "25004" => Some(inappropriate_isolation_level_for_branch_transaction)
      case "25005" => Some(no_active_sql_transaction_for_branch_transaction)
      case "25006" => Some(read_only_sql_transaction)
      case "25007" => Some(schema_and_data_statement_mixing_not_supported)
      case "25P01" => Some(no_active_sql_transaction)
      case "25P02" => Some(in_failed_sql_transaction)
      case "25P03" => Some(idle_in_transaction_session_timeout)
      case "26000" => Some(invalid_sql_statement_name)
      case "27000" => Some(triggered_data_change_violation)
      case "28000" => Some(invalid_authorization_specification)
      case "28P01" => Some(invalid_password)
      case "2B000" => Some(dependent_privilege_descriptors_still_exist)
      case "2BP01" => Some(dependent_objects_still_exist)
      case "2D000" => Some(invalid_transaction_termination)
      case "2F000" => Some(sql_routine_exception)
      case "2F005" => Some(function_executed_no_return_statement)
      case "2F002" => Some(modifying_sql_data_not_permitted)
      case "2F003" => Some(prohibited_sql_statement_attempted)
      case "2F004" => Some(reading_sql_data_not_permitted)
      case "34000" => Some(invalid_cursor_name)
      case "38000" => Some(external_routine_exception)
      case "38001" => Some(containing_sql_not_permitted)
      case "38002" => Some(modifying_sql_data_not_permitted)
      case "38003" => Some(prohibited_sql_statement_attempted)
      case "38004" => Some(reading_sql_data_not_permitted)
      case "39000" => Some(external_routine_invocation_exception)
      case "39001" => Some(invalid_sqlstate_returned)
      case "39004" => Some(null_value_not_allowed)
      case "39P01" => Some(trigger_protocol_violated)
      case "39P02" => Some(srf_protocol_violated)
      case "39P03" => Some(event_trigger_protocol_violated)
      case "3B000" => Some(savepoint_exception)
      case "3B001" => Some(invalid_savepoint_specification)
      case "3D000" => Some(invalid_catalog_name)
      case "3F000" => Some(invalid_schema_name)
      case "40000" => Some(transaction_rollback)
      case "40002" => Some(transaction_integrity_constraint_violation)
      case "40001" => Some(serialization_failure)
      case "40003" => Some(statement_completion_unknown)
      case "40P01" => Some(deadlock_detected)
      case "42000" => Some(syntax_error_or_access_rule_violation)
      case "42601" => Some(syntax_error)
      case "42501" => Some(insufficient_privilege)
      case "42846" => Some(cannot_coerce)
      case "42803" => Some(grouping_error)
      case "42P20" => Some(windowing_error)
      case "42P19" => Some(invalid_recursion)
      case "42830" => Some(invalid_foreign_key)
      case "42602" => Some(invalid_name)
      case "42622" => Some(name_too_long)
      case "42939" => Some(reserved_name)
      case "42804" => Some(datatype_mismatch)
      case "42P18" => Some(indeterminate_datatype)
      case "42P21" => Some(collation_mismatch)
      case "42P22" => Some(indeterminate_collation)
      case "42809" => Some(wrong_object_type)
      case "428C9" => Some(generated_always)
      case "42703" => Some(undefined_column)
      case "42883" => Some(undefined_function)
      case "42P01" => Some(undefined_table)
      case "42P02" => Some(undefined_parameter)
      case "42704" => Some(undefined_object)
      case "42701" => Some(duplicate_column)
      case "42P03" => Some(duplicate_cursor)
      case "42P04" => Some(duplicate_database)
      case "42723" => Some(duplicate_function)
      case "42P05" => Some(duplicate_prepared_statement)
      case "42P06" => Some(duplicate_schema)
      case "42P07" => Some(duplicate_table)
      case "42712" => Some(duplicate_alias)
      case "42710" => Some(duplicate_object)
      case "42702" => Some(ambiguous_column)
      case "42725" => Some(ambiguous_function)
      case "42P08" => Some(ambiguous_parameter)
      case "42P09" => Some(ambiguous_alias)
      case "42P10" => Some(invalid_column_reference)
      case "42611" => Some(invalid_column_definition)
      case "42P11" => Some(invalid_cursor_definition)
      case "42P12" => Some(invalid_database_definition)
      case "42P13" => Some(invalid_function_definition)
      case "42P14" => Some(invalid_prepared_statement_definition)
      case "42P15" => Some(invalid_schema_definition)
      case "42P16" => Some(invalid_table_definition)
      case "42P17" => Some(invalid_object_definition)
      case "44000" => Some(with_check_option_violation)
      case "53000" => Some(insufficient_resources)
      case "53100" => Some(disk_full)
      case "53200" => Some(out_of_memory)
      case "53300" => Some(too_many_connections)
      case "53400" => Some(configuration_limit_exceeded)
      case "54000" => Some(program_limit_exceeded)
      case "54001" => Some(statement_too_complex)
      case "54011" => Some(too_many_columns)
      case "54023" => Some(too_many_arguments)
      case "55000" => Some(object_not_in_prerequisite_state)
      case "55006" => Some(object_in_use)
      case "55P02" => Some(cant_change_runtime_param)
      case "55P03" => Some(lock_not_available)
      case "55P04" => Some(unsafe_new_enum_value_usage)
      case "57000" => Some(operator_intervention)
      case "57014" => Some(query_canceled)
      case "57P01" => Some(admin_shutdown)
      case "57P02" => Some(crash_shutdown)
      case "57P03" => Some(cannot_connect_now)
      case "57P04" => Some(database_dropped)
      case "57P05" => Some(idle_session_timeout)
      case "58000" => Some(system_error)
      case "58030" => Some(io_error)
      case "58P01" => Some(undefined_file)
      case "58P02" => Some(duplicate_file)
      case "72000" => Some(snapshot_too_old)
      case "F0000" => Some(config_file_error)
      case "F0001" => Some(lock_file_exists)
      case "HV000" => Some(fdw_error)
      case "HV005" => Some(fdw_column_name_not_found)
      case "HV002" => Some(fdw_dynamic_parameter_value_needed)
      case "HV010" => Some(fdw_function_sequence_error)
      case "HV021" => Some(fdw_inconsistent_descriptor_information)
      case "HV024" => Some(fdw_invalid_attribute_value)
      case "HV007" => Some(fdw_invalid_column_name)
      case "HV008" => Some(fdw_invalid_column_number)
      case "HV004" => Some(fdw_invalid_data_type)
      case "HV006" => Some(fdw_invalid_data_type_descriptors)
      case "HV091" => Some(fdw_invalid_descriptor_field_identifier)
      case "HV00B" => Some(fdw_invalid_handle)
      case "HV00C" => Some(fdw_invalid_option_index)
      case "HV00D" => Some(fdw_invalid_option_name)
      case "HV090" => Some(fdw_invalid_string_length_or_buffer_length)
      case "HV00A" => Some(fdw_invalid_string_format)
      case "HV009" => Some(fdw_invalid_use_of_null_pointer)
      case "HV014" => Some(fdw_too_many_handles)
      case "HV001" => Some(fdw_out_of_memory)
      case "HV00P" => Some(fdw_no_schemas)
      case "HV00J" => Some(fdw_option_name_not_found)
      case "HV00K" => Some(fdw_reply_handle)
      case "HV00Q" => Some(fdw_schema_not_found)
      case "HV00R" => Some(fdw_table_not_found)
      case "HV00L" => Some(fdw_unable_to_create_execution)
      case "HV00M" => Some(fdw_unable_to_create_reply)
      case "HV00N" => Some(fdw_unable_to_establish_connection)
      case "P0000" => Some(plpgsql_error)
      case "P0001" => Some(raise_exception)
      case "P0002" => Some(no_data_found)
      case "P0003" => Some(too_many_rows)
      case "P0004" => Some(assert_failure)
      case "XX000" => Some(internal_error)
      case "XX001" => Some(data_corrupted)
      case "XX002" => Some(index_corrupted)
      case _       => None

  end lookup

  inline def inlineLookup(inline code: String): SQLSTATE =
    inline code match
      case "00000" => successful_completion
      case "01000" => warning
      case "0100C" => dynamic_result_sets_returned
      case "01008" => implicit_zero_bit_padding
      case "01003" => null_value_eliminated_in_set_function
      case "01007" => privilege_not_granted
      case "01006" => privilege_not_revoked
      case "01004" => string_data_right_truncation
      case "01P01" => deprecated_feature
      case "02000" => no_data
      case "02001" => no_additional_dynamic_result_sets_returned
      case "03000" => sql_statement_not_yet_complete
      case "08000" => connection_exception
      case "08003" => connection_does_not_exist
      case "08006" => connection_failure
      case "08001" => sqlclient_unable_to_establish_sqlconnection
      case "08004" => sqlserver_rejected_establishment_of_sqlconnection
      case "08007" => transaction_resolution_unknown
      case "08P01" => protocol_violation
      case "09000" => triggered_action_exception
      case "0A000" => feature_not_supported
      case "0B000" => invalid_transaction_initiation
      case "0F000" => locator_exception
      case "0F001" => invalid_locator_specification
      case "0L000" => invalid_grantor
      case "0LP01" => invalid_grant_operation
      case "0P000" => invalid_role_specification
      case "0Z000" => diagnostics_exception
      case "0Z002" => stacked_diagnostics_accessed_without_active_handler
      case "20000" => case_not_found
      case "21000" => cardinality_violation
      case "22000" => data_exception
      case "2202E" => array_subscript_error
      case "22021" => character_not_in_repertoire
      case "22008" => datetime_field_overflow
      case "22012" => division_by_zero
      case "22005" => error_in_assignment
      case "2200B" => escape_character_conflict
      case "22022" => indicator_overflow
      case "22015" => interval_field_overflow
      case "2201E" => invalid_argument_for_logarithm
      case "22014" => invalid_argument_for_ntile_function
      case "22016" => invalid_argument_for_nth_value_function
      case "2201F" => invalid_argument_for_power_function
      case "2201G" => invalid_argument_for_width_bucket_function
      case "22018" => invalid_character_value_for_cast
      case "22007" => invalid_datetime_format
      case "22019" => invalid_escape_character
      case "2200D" => invalid_escape_octet
      case "22025" => invalid_escape_sequence
      case "22P06" => nonstandard_use_of_escape_character
      case "22010" => invalid_indicator_parameter_value
      case "22023" => invalid_parameter_value
      case "22013" => invalid_preceding_or_following_size
      case "2201B" => invalid_regular_expression
      case "2201W" => invalid_row_count_in_limit_clause
      case "2201X" => invalid_row_count_in_result_offset_clause
      case "2202H" => invalid_tablesample_argument
      case "2202G" => invalid_tablesample_repeat
      case "22009" => invalid_time_zone_displacement_value
      case "2200C" => invalid_use_of_escape_character
      case "2200G" => most_specific_type_mismatch
      case "22004" => null_value_not_allowed
      case "22002" => null_value_no_indicator_parameter
      case "22003" => numeric_value_out_of_range
      case "2200H" => sequence_generator_limit_exceeded
      case "22026" => string_data_length_mismatch
      case "22001" => string_data_right_truncation
      case "22011" => substring_error
      case "22027" => trim_error
      case "22024" => unterminated_c_string
      case "2200F" => zero_length_character_string
      case "22P01" => floating_point_exception
      case "22P02" => invalid_text_representation
      case "22P03" => invalid_binary_representation
      case "22P04" => bad_copy_file_format
      case "22P05" => untranslatable_character
      case "2200L" => not_an_xml_document
      case "2200M" => invalid_xml_document
      case "2200N" => invalid_xml_content
      case "2200S" => invalid_xml_comment
      case "2200T" => invalid_xml_processing_instruction
      case "22030" => duplicate_json_object_key_value
      case "22031" => invalid_argument_for_sql_json_datetime_function
      case "22032" => invalid_json_text
      case "22033" => invalid_sql_json_subscript
      case "22034" => more_than_one_sql_json_item
      case "22035" => no_sql_json_item
      case "22036" => non_numeric_sql_json_item
      case "22037" => non_unique_keys_in_a_json_object
      case "22038" => singleton_sql_json_item_required
      case "22039" => sql_json_array_not_found
      case "2203A" => sql_json_member_not_found
      case "2203B" => sql_json_number_not_found
      case "2203C" => sql_json_object_not_found
      case "2203D" => too_many_json_array_elements
      case "2203E" => too_many_json_object_members
      case "2203F" => sql_json_scalar_required
      case "2203G" => sql_json_item_cannot_be_cast_to_target_type
      case "23000" => integrity_constraint_violation
      case "23001" => restrict_violation
      case "23502" => not_null_violation
      case "23503" => foreign_key_violation
      case "23505" => unique_violation
      case "23514" => check_violation
      case "23P01" => exclusion_violation
      case "24000" => invalid_cursor_state
      case "25000" => invalid_transaction_state
      case "25001" => active_sql_transaction
      case "25002" => branch_transaction_already_active
      case "25008" => held_cursor_requires_same_isolation_level
      case "25003" => inappropriate_access_mode_for_branch_transaction
      case "25004" => inappropriate_isolation_level_for_branch_transaction
      case "25005" => no_active_sql_transaction_for_branch_transaction
      case "25006" => read_only_sql_transaction
      case "25007" => schema_and_data_statement_mixing_not_supported
      case "25P01" => no_active_sql_transaction
      case "25P02" => in_failed_sql_transaction
      case "25P03" => idle_in_transaction_session_timeout
      case "26000" => invalid_sql_statement_name
      case "27000" => triggered_data_change_violation
      case "28000" => invalid_authorization_specification
      case "28P01" => invalid_password
      case "2B000" => dependent_privilege_descriptors_still_exist
      case "2BP01" => dependent_objects_still_exist
      case "2D000" => invalid_transaction_termination
      case "2F000" => sql_routine_exception
      case "2F005" => function_executed_no_return_statement
      case "2F002" => modifying_sql_data_not_permitted
      case "2F003" => prohibited_sql_statement_attempted
      case "2F004" => reading_sql_data_not_permitted
      case "34000" => invalid_cursor_name
      case "38000" => external_routine_exception
      case "38001" => containing_sql_not_permitted
      case "38002" => modifying_sql_data_not_permitted
      case "38003" => prohibited_sql_statement_attempted
      case "38004" => reading_sql_data_not_permitted
      case "39000" => external_routine_invocation_exception
      case "39001" => invalid_sqlstate_returned
      case "39004" => null_value_not_allowed
      case "39P01" => trigger_protocol_violated
      case "39P02" => srf_protocol_violated
      case "39P03" => event_trigger_protocol_violated
      case "3B000" => savepoint_exception
      case "3B001" => invalid_savepoint_specification
      case "3D000" => invalid_catalog_name
      case "3F000" => invalid_schema_name
      case "40000" => transaction_rollback
      case "40002" => transaction_integrity_constraint_violation
      case "40001" => serialization_failure
      case "40003" => statement_completion_unknown
      case "40P01" => deadlock_detected
      case "42000" => syntax_error_or_access_rule_violation
      case "42601" => syntax_error
      case "42501" => insufficient_privilege
      case "42846" => cannot_coerce
      case "42803" => grouping_error
      case "42P20" => windowing_error
      case "42P19" => invalid_recursion
      case "42830" => invalid_foreign_key
      case "42602" => invalid_name
      case "42622" => name_too_long
      case "42939" => reserved_name
      case "42804" => datatype_mismatch
      case "42P18" => indeterminate_datatype
      case "42P21" => collation_mismatch
      case "42P22" => indeterminate_collation
      case "42809" => wrong_object_type
      case "428C9" => generated_always
      case "42703" => undefined_column
      case "42883" => undefined_function
      case "42P01" => undefined_table
      case "42P02" => undefined_parameter
      case "42704" => undefined_object
      case "42701" => duplicate_column
      case "42P03" => duplicate_cursor
      case "42P04" => duplicate_database
      case "42723" => duplicate_function
      case "42P05" => duplicate_prepared_statement
      case "42P06" => duplicate_schema
      case "42P07" => duplicate_table
      case "42712" => duplicate_alias
      case "42710" => duplicate_object
      case "42702" => ambiguous_column
      case "42725" => ambiguous_function
      case "42P08" => ambiguous_parameter
      case "42P09" => ambiguous_alias
      case "42P10" => invalid_column_reference
      case "42611" => invalid_column_definition
      case "42P11" => invalid_cursor_definition
      case "42P12" => invalid_database_definition
      case "42P13" => invalid_function_definition
      case "42P14" => invalid_prepared_statement_definition
      case "42P15" => invalid_schema_definition
      case "42P16" => invalid_table_definition
      case "42P17" => invalid_object_definition
      case "44000" => with_check_option_violation
      case "53000" => insufficient_resources
      case "53100" => disk_full
      case "53200" => out_of_memory
      case "53300" => too_many_connections
      case "53400" => configuration_limit_exceeded
      case "54000" => program_limit_exceeded
      case "54001" => statement_too_complex
      case "54011" => too_many_columns
      case "54023" => too_many_arguments
      case "55000" => object_not_in_prerequisite_state
      case "55006" => object_in_use
      case "55P02" => cant_change_runtime_param
      case "55P03" => lock_not_available
      case "55P04" => unsafe_new_enum_value_usage
      case "57000" => operator_intervention
      case "57014" => query_canceled
      case "57P01" => admin_shutdown
      case "57P02" => crash_shutdown
      case "57P03" => cannot_connect_now
      case "57P04" => database_dropped
      case "57P05" => idle_session_timeout
      case "58000" => system_error
      case "58030" => io_error
      case "58P01" => undefined_file
      case "58P02" => duplicate_file
      case "72000" => snapshot_too_old
      case "F0000" => config_file_error
      case "F0001" => lock_file_exists
      case "HV000" => fdw_error
      case "HV005" => fdw_column_name_not_found
      case "HV002" => fdw_dynamic_parameter_value_needed
      case "HV010" => fdw_function_sequence_error
      case "HV021" => fdw_inconsistent_descriptor_information
      case "HV024" => fdw_invalid_attribute_value
      case "HV007" => fdw_invalid_column_name
      case "HV008" => fdw_invalid_column_number
      case "HV004" => fdw_invalid_data_type
      case "HV006" => fdw_invalid_data_type_descriptors
      case "HV091" => fdw_invalid_descriptor_field_identifier
      case "HV00B" => fdw_invalid_handle
      case "HV00C" => fdw_invalid_option_index
      case "HV00D" => fdw_invalid_option_name
      case "HV090" => fdw_invalid_string_length_or_buffer_length
      case "HV00A" => fdw_invalid_string_format
      case "HV009" => fdw_invalid_use_of_null_pointer
      case "HV014" => fdw_too_many_handles
      case "HV001" => fdw_out_of_memory
      case "HV00P" => fdw_no_schemas
      case "HV00J" => fdw_option_name_not_found
      case "HV00K" => fdw_reply_handle
      case "HV00Q" => fdw_schema_not_found
      case "HV00R" => fdw_table_not_found
      case "HV00L" => fdw_unable_to_create_execution
      case "HV00M" => fdw_unable_to_create_reply
      case "HV00N" => fdw_unable_to_establish_connection
      case "P0000" => plpgsql_error
      case "P0001" => raise_exception
      case "P0002" => no_data_found
      case "P0003" => too_many_rows
      case "P0004" => assert_failure
      case "XX000" => internal_error
      case "XX001" => data_corrupted
      case "XX002" => index_corrupted

  end inlineLookup

  @annotation.targetName("lookup_code")
  def code(sqlState: SQLSTATE): Option[String] | List[String] =
    sqlState match
      case "successful_completion"                 => Some("00000")
      case "warning"                               => Some("01000")
      case "dynamic_result_sets_returned"          => Some("0100C")
      case "implicit_zero_bit_padding"             => Some("01008")
      case "null_value_eliminated_in_set_function" => Some("01003")
      case "privilege_not_granted"                 => Some("01007")
      case "privilege_not_revoked"                 => Some("01006")
      case "string_data_right_truncation"          => List("01004", "22001")
      case "deprecated_feature"                    => Some("01P01")
      case "no_data"                               => Some("02000")
      case "no_additional_dynamic_result_sets_returned"        => Some("02001")
      case "sql_statement_not_yet_complete"                    => Some("03000")
      case "connection_exception"                              => Some("08000")
      case "connection_does_not_exist"                         => Some("08003")
      case "connection_failure"                                => Some("08006")
      case "sqlclient_unable_to_establish_sqlconnection"       => Some("08001")
      case "sqlserver_rejected_establishment_of_sqlconnection" => Some("08004")
      case "transaction_resolution_unknown"                    => Some("08007")
      case "protocol_violation"                                => Some("08P01")
      case "triggered_action_exception"                        => Some("09000")
      case "feature_not_supported"                             => Some("0A000")
      case "invalid_transaction_initiation"                    => Some("0B000")
      case "locator_exception"                                 => Some("0F000")
      case "invalid_locator_specification"                     => Some("0F001")
      case "invalid_grantor"                                   => Some("0L000")
      case "invalid_grant_operation"                           => Some("0LP01")
      case "invalid_role_specification"                        => Some("0P000")
      case "diagnostics_exception"                             => Some("0Z000")
      case "stacked_diagnostics_accessed_without_active_handler" =>
        Some("0Z002")
      case "case_not_found"                             => Some("20000")
      case "cardinality_violation"                      => Some("21000")
      case "data_exception"                             => Some("22000")
      case "array_subscript_error"                      => Some("2202E")
      case "character_not_in_repertoire"                => Some("22021")
      case "datetime_field_overflow"                    => Some("22008")
      case "division_by_zero"                           => Some("22012")
      case "error_in_assignment"                        => Some("22005")
      case "escape_character_conflict"                  => Some("2200B")
      case "indicator_overflow"                         => Some("22022")
      case "interval_field_overflow"                    => Some("22015")
      case "invalid_argument_for_logarithm"             => Some("2201E")
      case "invalid_argument_for_ntile_function"        => Some("22014")
      case "invalid_argument_for_nth_value_function"    => Some("22016")
      case "invalid_argument_for_power_function"        => Some("2201F")
      case "invalid_argument_for_width_bucket_function" => Some("2201G")
      case "invalid_character_value_for_cast"           => Some("22018")
      case "invalid_datetime_format"                    => Some("22007")
      case "invalid_escape_character"                   => Some("22019")
      case "invalid_escape_octet"                       => Some("2200D")
      case "invalid_escape_sequence"                    => Some("22025")
      case "nonstandard_use_of_escape_character"        => Some("22P06")
      case "invalid_indicator_parameter_value"          => Some("22010")
      case "invalid_parameter_value"                    => Some("22023")
      case "invalid_preceding_or_following_size"        => Some("22013")
      case "invalid_regular_expression"                 => Some("2201B")
      case "invalid_row_count_in_limit_clause"          => Some("2201W")
      case "invalid_row_count_in_result_offset_clause"  => Some("2201X")
      case "invalid_tablesample_argument"               => Some("2202H")
      case "invalid_tablesample_repeat"                 => Some("2202G")
      case "invalid_time_zone_displacement_value"       => Some("22009")
      case "invalid_use_of_escape_character"            => Some("2200C")
      case "most_specific_type_mismatch"                => Some("2200G")
      case "null_value_not_allowed"             => List("22004", "39004")
      case "null_value_no_indicator_parameter"  => Some("22002")
      case "numeric_value_out_of_range"         => Some("22003")
      case "sequence_generator_limit_exceeded"  => Some("2200H")
      case "string_data_length_mismatch"        => Some("22026")
      case "string_data_right_truncation"       => List("01004", "22001")
      case "substring_error"                    => Some("22011")
      case "trim_error"                         => Some("22027")
      case "unterminated_c_string"              => Some("22024")
      case "zero_length_character_string"       => Some("2200F")
      case "floating_point_exception"           => Some("22P01")
      case "invalid_text_representation"        => Some("22P02")
      case "invalid_binary_representation"      => Some("22P03")
      case "bad_copy_file_format"               => Some("22P04")
      case "untranslatable_character"           => Some("22P05")
      case "not_an_xml_document"                => Some("2200L")
      case "invalid_xml_document"               => Some("2200M")
      case "invalid_xml_content"                => Some("2200N")
      case "invalid_xml_comment"                => Some("2200S")
      case "invalid_xml_processing_instruction" => Some("2200T")
      case "duplicate_json_object_key_value"    => Some("22030")
      case "invalid_argument_for_sql_json_datetime_function"  => Some("22031")
      case "invalid_json_text"                                => Some("22032")
      case "invalid_sql_json_subscript"                       => Some("22033")
      case "more_than_one_sql_json_item"                      => Some("22034")
      case "no_sql_json_item"                                 => Some("22035")
      case "non_numeric_sql_json_item"                        => Some("22036")
      case "non_unique_keys_in_a_json_object"                 => Some("22037")
      case "singleton_sql_json_item_required"                 => Some("22038")
      case "sql_json_array_not_found"                         => Some("22039")
      case "sql_json_member_not_found"                        => Some("2203A")
      case "sql_json_number_not_found"                        => Some("2203B")
      case "sql_json_object_not_found"                        => Some("2203C")
      case "too_many_json_array_elements"                     => Some("2203D")
      case "too_many_json_object_members"                     => Some("2203E")
      case "sql_json_scalar_required"                         => Some("2203F")
      case "sql_json_item_cannot_be_cast_to_target_type"      => Some("2203G")
      case "integrity_constraint_violation"                   => Some("23000")
      case "restrict_violation"                               => Some("23001")
      case "not_null_violation"                               => Some("23502")
      case "foreign_key_violation"                            => Some("23503")
      case "unique_violation"                                 => Some("23505")
      case "check_violation"                                  => Some("23514")
      case "exclusion_violation"                              => Some("23P01")
      case "invalid_cursor_state"                             => Some("24000")
      case "invalid_transaction_state"                        => Some("25000")
      case "active_sql_transaction"                           => Some("25001")
      case "branch_transaction_already_active"                => Some("25002")
      case "held_cursor_requires_same_isolation_level"        => Some("25008")
      case "inappropriate_access_mode_for_branch_transaction" => Some("25003")
      case "inappropriate_isolation_level_for_branch_transaction" =>
        Some("25004")
      case "no_active_sql_transaction_for_branch_transaction" => Some("25005")
      case "read_only_sql_transaction"                        => Some("25006")
      case "schema_and_data_statement_mixing_not_supported"   => Some("25007")
      case "no_active_sql_transaction"                        => Some("25P01")
      case "in_failed_sql_transaction"                        => Some("25P02")
      case "idle_in_transaction_session_timeout"              => Some("25P03")
      case "invalid_sql_statement_name"                       => Some("26000")
      case "triggered_data_change_violation"                  => Some("27000")
      case "invalid_authorization_specification"              => Some("28000")
      case "invalid_password"                                 => Some("28P01")
      case "dependent_privilege_descriptors_still_exist"      => Some("2B000")
      case "dependent_objects_still_exist"                    => Some("2BP01")
      case "invalid_transaction_termination"                  => Some("2D000")
      case "sql_routine_exception"                            => Some("2F000")
      case "function_executed_no_return_statement"            => Some("2F005")
      case "modifying_sql_data_not_permitted"      => List("2F002", "38002")
      case "prohibited_sql_statement_attempted"    => List("2F003", "38003")
      case "reading_sql_data_not_permitted"        => List("2F004", "38004")
      case "invalid_cursor_name"                   => Some("34000")
      case "external_routine_exception"            => Some("38000")
      case "containing_sql_not_permitted"          => Some("38001")
      case "modifying_sql_data_not_permitted"      => List("2F002", "38002")
      case "prohibited_sql_statement_attempted"    => List("2F003", "38003")
      case "reading_sql_data_not_permitted"        => List("2F004", "38004")
      case "external_routine_invocation_exception" => Some("39000")
      case "invalid_sqlstate_returned"             => Some("39001")
      case "null_value_not_allowed"                => List("22004", "39004")
      case "trigger_protocol_violated"             => Some("39P01")
      case "srf_protocol_violated"                 => Some("39P02")
      case "event_trigger_protocol_violated"       => Some("39P03")
      case "savepoint_exception"                   => Some("3B000")
      case "invalid_savepoint_specification"       => Some("3B001")
      case "invalid_catalog_name"                  => Some("3D000")
      case "invalid_schema_name"                   => Some("3F000")
      case "transaction_rollback"                  => Some("40000")
      case "transaction_integrity_constraint_violation" => Some("40002")
      case "serialization_failure"                      => Some("40001")
      case "statement_completion_unknown"               => Some("40003")
      case "deadlock_detected"                          => Some("40P01")
      case "syntax_error_or_access_rule_violation"      => Some("42000")
      case "syntax_error"                               => Some("42601")
      case "insufficient_privilege"                     => Some("42501")
      case "cannot_coerce"                              => Some("42846")
      case "grouping_error"                             => Some("42803")
      case "windowing_error"                            => Some("42P20")
      case "invalid_recursion"                          => Some("42P19")
      case "invalid_foreign_key"                        => Some("42830")
      case "invalid_name"                               => Some("42602")
      case "name_too_long"                              => Some("42622")
      case "reserved_name"                              => Some("42939")
      case "datatype_mismatch"                          => Some("42804")
      case "indeterminate_datatype"                     => Some("42P18")
      case "collation_mismatch"                         => Some("42P21")
      case "indeterminate_collation"                    => Some("42P22")
      case "wrong_object_type"                          => Some("42809")
      case "generated_always"                           => Some("428C9")
      case "undefined_column"                           => Some("42703")
      case "undefined_function"                         => Some("42883")
      case "undefined_table"                            => Some("42P01")
      case "undefined_parameter"                        => Some("42P02")
      case "undefined_object"                           => Some("42704")
      case "duplicate_column"                           => Some("42701")
      case "duplicate_cursor"                           => Some("42P03")
      case "duplicate_database"                         => Some("42P04")
      case "duplicate_function"                         => Some("42723")
      case "duplicate_prepared_statement"               => Some("42P05")
      case "duplicate_schema"                           => Some("42P06")
      case "duplicate_table"                            => Some("42P07")
      case "duplicate_alias"                            => Some("42712")
      case "duplicate_object"                           => Some("42710")
      case "ambiguous_column"                           => Some("42702")
      case "ambiguous_function"                         => Some("42725")
      case "ambiguous_parameter"                        => Some("42P08")
      case "ambiguous_alias"                            => Some("42P09")
      case "invalid_column_reference"                   => Some("42P10")
      case "invalid_column_definition"                  => Some("42611")
      case "invalid_cursor_definition"                  => Some("42P11")
      case "invalid_database_definition"                => Some("42P12")
      case "invalid_function_definition"                => Some("42P13")
      case "invalid_prepared_statement_definition"      => Some("42P14")
      case "invalid_schema_definition"                  => Some("42P15")
      case "invalid_table_definition"                   => Some("42P16")
      case "invalid_object_definition"                  => Some("42P17")
      case "with_check_option_violation"                => Some("44000")
      case "insufficient_resources"                     => Some("53000")
      case "disk_full"                                  => Some("53100")
      case "out_of_memory"                              => Some("53200")
      case "too_many_connections"                       => Some("53300")
      case "configuration_limit_exceeded"               => Some("53400")
      case "program_limit_exceeded"                     => Some("54000")
      case "statement_too_complex"                      => Some("54001")
      case "too_many_columns"                           => Some("54011")
      case "too_many_arguments"                         => Some("54023")
      case "object_not_in_prerequisite_state"           => Some("55000")
      case "object_in_use"                              => Some("55006")
      case "cant_change_runtime_param"                  => Some("55P02")
      case "lock_not_available"                         => Some("55P03")
      case "unsafe_new_enum_value_usage"                => Some("55P04")
      case "operator_intervention"                      => Some("57000")
      case "query_canceled"                             => Some("57014")
      case "admin_shutdown"                             => Some("57P01")
      case "crash_shutdown"                             => Some("57P02")
      case "cannot_connect_now"                         => Some("57P03")
      case "database_dropped"                           => Some("57P04")
      case "idle_session_timeout"                       => Some("57P05")
      case "system_error"                               => Some("58000")
      case "io_error"                                   => Some("58030")
      case "undefined_file"                             => Some("58P01")
      case "duplicate_file"                             => Some("58P02")
      case "snapshot_too_old"                           => Some("72000")
      case "config_file_error"                          => Some("F0000")
      case "lock_file_exists"                           => Some("F0001")
      case "fdw_error"                                  => Some("HV000")
      case "fdw_column_name_not_found"                  => Some("HV005")
      case "fdw_dynamic_parameter_value_needed"         => Some("HV002")
      case "fdw_function_sequence_error"                => Some("HV010")
      case "fdw_inconsistent_descriptor_information"    => Some("HV021")
      case "fdw_invalid_attribute_value"                => Some("HV024")
      case "fdw_invalid_column_name"                    => Some("HV007")
      case "fdw_invalid_column_number"                  => Some("HV008")
      case "fdw_invalid_data_type"                      => Some("HV004")
      case "fdw_invalid_data_type_descriptors"          => Some("HV006")
      case "fdw_invalid_descriptor_field_identifier"    => Some("HV091")
      case "fdw_invalid_handle"                         => Some("HV00B")
      case "fdw_invalid_option_index"                   => Some("HV00C")
      case "fdw_invalid_option_name"                    => Some("HV00D")
      case "fdw_invalid_string_length_or_buffer_length" => Some("HV090")
      case "fdw_invalid_string_format"                  => Some("HV00A")
      case "fdw_invalid_use_of_null_pointer"            => Some("HV009")
      case "fdw_too_many_handles"                       => Some("HV014")
      case "fdw_out_of_memory"                          => Some("HV001")
      case "fdw_no_schemas"                             => Some("HV00P")
      case "fdw_option_name_not_found"                  => Some("HV00J")
      case "fdw_reply_handle"                           => Some("HV00K")
      case "fdw_schema_not_found"                       => Some("HV00Q")
      case "fdw_table_not_found"                        => Some("HV00R")
      case "fdw_unable_to_create_execution"             => Some("HV00L")
      case "fdw_unable_to_create_reply"                 => Some("HV00M")
      case "fdw_unable_to_establish_connection"         => Some("HV00N")
      case "plpgsql_error"                              => Some("P0000")
      case "raise_exception"                            => Some("P0001")
      case "no_data_found"                              => Some("P0002")
      case "too_many_rows"                              => Some("P0003")
      case "assert_failure"                             => Some("P0004")
      case "internal_error"                             => Some("XX000")
      case "data_corrupted"                             => Some("XX001")
      case "index_corrupted"                            => Some("XX002")
      case _                                            => None

  end code

  transparent inline def inlineCode(
      inline sqlState: SQLSTATE
  ): String | (String, String) =
    inline sqlState match
      case "successful_completion"                       => "00000"
      case "warning"                                     => "01000"
      case "dynamic_result_sets_returned"                => "0100C"
      case "implicit_zero_bit_padding"                   => "01008"
      case "null_value_eliminated_in_set_function"       => "01003"
      case "privilege_not_granted"                       => "01007"
      case "privilege_not_revoked"                       => "01006"
      case "string_data_right_truncation"                => ("01004", "22001")
      case "deprecated_feature"                          => "01P01"
      case "no_data"                                     => "02000"
      case "no_additional_dynamic_result_sets_returned"  => "02001"
      case "sql_statement_not_yet_complete"              => "03000"
      case "connection_exception"                        => "08000"
      case "connection_does_not_exist"                   => "08003"
      case "connection_failure"                          => "08006"
      case "sqlclient_unable_to_establish_sqlconnection" => "08001"
      case "sqlserver_rejected_establishment_of_sqlconnection"   => "08004"
      case "transaction_resolution_unknown"                      => "08007"
      case "protocol_violation"                                  => "08P01"
      case "triggered_action_exception"                          => "09000"
      case "feature_not_supported"                               => "0A000"
      case "invalid_transaction_initiation"                      => "0B000"
      case "locator_exception"                                   => "0F000"
      case "invalid_locator_specification"                       => "0F001"
      case "invalid_grantor"                                     => "0L000"
      case "invalid_grant_operation"                             => "0LP01"
      case "invalid_role_specification"                          => "0P000"
      case "diagnostics_exception"                               => "0Z000"
      case "stacked_diagnostics_accessed_without_active_handler" => "0Z002"
      case "case_not_found"                                      => "20000"
      case "cardinality_violation"                               => "21000"
      case "data_exception"                                      => "22000"
      case "array_subscript_error"                               => "2202E"
      case "character_not_in_repertoire"                         => "22021"
      case "datetime_field_overflow"                             => "22008"
      case "division_by_zero"                                    => "22012"
      case "error_in_assignment"                                 => "22005"
      case "escape_character_conflict"                           => "2200B"
      case "indicator_overflow"                                  => "22022"
      case "interval_field_overflow"                             => "22015"
      case "invalid_argument_for_logarithm"                      => "2201E"
      case "invalid_argument_for_ntile_function"                 => "22014"
      case "invalid_argument_for_nth_value_function"             => "22016"
      case "invalid_argument_for_power_function"                 => "2201F"
      case "invalid_argument_for_width_bucket_function"          => "2201G"
      case "invalid_character_value_for_cast"                    => "22018"
      case "invalid_datetime_format"                             => "22007"
      case "invalid_escape_character"                            => "22019"
      case "invalid_escape_octet"                                => "2200D"
      case "invalid_escape_sequence"                             => "22025"
      case "nonstandard_use_of_escape_character"                 => "22P06"
      case "invalid_indicator_parameter_value"                   => "22010"
      case "invalid_parameter_value"                             => "22023"
      case "invalid_preceding_or_following_size"                 => "22013"
      case "invalid_regular_expression"                          => "2201B"
      case "invalid_row_count_in_limit_clause"                   => "2201W"
      case "invalid_row_count_in_result_offset_clause"           => "2201X"
      case "invalid_tablesample_argument"                        => "2202H"
      case "invalid_tablesample_repeat"                          => "2202G"
      case "invalid_time_zone_displacement_value"                => "22009"
      case "invalid_use_of_escape_character"                     => "2200C"
      case "most_specific_type_mismatch"                         => "2200G"
      case "null_value_not_allowed"             => ("22004", "39004")
      case "null_value_no_indicator_parameter"  => "22002"
      case "numeric_value_out_of_range"         => "22003"
      case "sequence_generator_limit_exceeded"  => "2200H"
      case "string_data_length_mismatch"        => "22026"
      case "string_data_right_truncation"       => ("01004", "22001")
      case "substring_error"                    => "22011"
      case "trim_error"                         => "22027"
      case "unterminated_c_string"              => "22024"
      case "zero_length_character_string"       => "2200F"
      case "floating_point_exception"           => "22P01"
      case "invalid_text_representation"        => "22P02"
      case "invalid_binary_representation"      => "22P03"
      case "bad_copy_file_format"               => "22P04"
      case "untranslatable_character"           => "22P05"
      case "not_an_xml_document"                => "2200L"
      case "invalid_xml_document"               => "2200M"
      case "invalid_xml_content"                => "2200N"
      case "invalid_xml_comment"                => "2200S"
      case "invalid_xml_processing_instruction" => "2200T"
      case "duplicate_json_object_key_value"    => "22030"
      case "invalid_argument_for_sql_json_datetime_function"      => "22031"
      case "invalid_json_text"                                    => "22032"
      case "invalid_sql_json_subscript"                           => "22033"
      case "more_than_one_sql_json_item"                          => "22034"
      case "no_sql_json_item"                                     => "22035"
      case "non_numeric_sql_json_item"                            => "22036"
      case "non_unique_keys_in_a_json_object"                     => "22037"
      case "singleton_sql_json_item_required"                     => "22038"
      case "sql_json_array_not_found"                             => "22039"
      case "sql_json_member_not_found"                            => "2203A"
      case "sql_json_number_not_found"                            => "2203B"
      case "sql_json_object_not_found"                            => "2203C"
      case "too_many_json_array_elements"                         => "2203D"
      case "too_many_json_object_members"                         => "2203E"
      case "sql_json_scalar_required"                             => "2203F"
      case "sql_json_item_cannot_be_cast_to_target_type"          => "2203G"
      case "integrity_constraint_violation"                       => "23000"
      case "restrict_violation"                                   => "23001"
      case "not_null_violation"                                   => "23502"
      case "foreign_key_violation"                                => "23503"
      case "unique_violation"                                     => "23505"
      case "check_violation"                                      => "23514"
      case "exclusion_violation"                                  => "23P01"
      case "invalid_cursor_state"                                 => "24000"
      case "invalid_transaction_state"                            => "25000"
      case "active_sql_transaction"                               => "25001"
      case "branch_transaction_already_active"                    => "25002"
      case "held_cursor_requires_same_isolation_level"            => "25008"
      case "inappropriate_access_mode_for_branch_transaction"     => "25003"
      case "inappropriate_isolation_level_for_branch_transaction" => "25004"
      case "no_active_sql_transaction_for_branch_transaction"     => "25005"
      case "read_only_sql_transaction"                            => "25006"
      case "schema_and_data_statement_mixing_not_supported"       => "25007"
      case "no_active_sql_transaction"                            => "25P01"
      case "in_failed_sql_transaction"                            => "25P02"
      case "idle_in_transaction_session_timeout"                  => "25P03"
      case "invalid_sql_statement_name"                           => "26000"
      case "triggered_data_change_violation"                      => "27000"
      case "invalid_authorization_specification"                  => "28000"
      case "invalid_password"                                     => "28P01"
      case "dependent_privilege_descriptors_still_exist"          => "2B000"
      case "dependent_objects_still_exist"                        => "2BP01"
      case "invalid_transaction_termination"                      => "2D000"
      case "sql_routine_exception"                                => "2F000"
      case "function_executed_no_return_statement"                => "2F005"
      case "modifying_sql_data_not_permitted"           => ("2F002", "38002")
      case "prohibited_sql_statement_attempted"         => ("2F003", "38003")
      case "reading_sql_data_not_permitted"             => ("2F004", "38004")
      case "invalid_cursor_name"                        => "34000"
      case "external_routine_exception"                 => "38000"
      case "containing_sql_not_permitted"               => "38001"
      case "modifying_sql_data_not_permitted"           => ("2F002", "38002")
      case "prohibited_sql_statement_attempted"         => ("2F003", "38003")
      case "reading_sql_data_not_permitted"             => ("2F004", "38004")
      case "external_routine_invocation_exception"      => "39000"
      case "invalid_sqlstate_returned"                  => "39001"
      case "null_value_not_allowed"                     => ("22004", "39004")
      case "trigger_protocol_violated"                  => "39P01"
      case "srf_protocol_violated"                      => "39P02"
      case "event_trigger_protocol_violated"            => "39P03"
      case "savepoint_exception"                        => "3B000"
      case "invalid_savepoint_specification"            => "3B001"
      case "invalid_catalog_name"                       => "3D000"
      case "invalid_schema_name"                        => "3F000"
      case "transaction_rollback"                       => "40000"
      case "transaction_integrity_constraint_violation" => "40002"
      case "serialization_failure"                      => "40001"
      case "statement_completion_unknown"               => "40003"
      case "deadlock_detected"                          => "40P01"
      case "syntax_error_or_access_rule_violation"      => "42000"
      case "syntax_error"                               => "42601"
      case "insufficient_privilege"                     => "42501"
      case "cannot_coerce"                              => "42846"
      case "grouping_error"                             => "42803"
      case "windowing_error"                            => "42P20"
      case "invalid_recursion"                          => "42P19"
      case "invalid_foreign_key"                        => "42830"
      case "invalid_name"                               => "42602"
      case "name_too_long"                              => "42622"
      case "reserved_name"                              => "42939"
      case "datatype_mismatch"                          => "42804"
      case "indeterminate_datatype"                     => "42P18"
      case "collation_mismatch"                         => "42P21"
      case "indeterminate_collation"                    => "42P22"
      case "wrong_object_type"                          => "42809"
      case "generated_always"                           => "428C9"
      case "undefined_column"                           => "42703"
      case "undefined_function"                         => "42883"
      case "undefined_table"                            => "42P01"
      case "undefined_parameter"                        => "42P02"
      case "undefined_object"                           => "42704"
      case "duplicate_column"                           => "42701"
      case "duplicate_cursor"                           => "42P03"
      case "duplicate_database"                         => "42P04"
      case "duplicate_function"                         => "42723"
      case "duplicate_prepared_statement"               => "42P05"
      case "duplicate_schema"                           => "42P06"
      case "duplicate_table"                            => "42P07"
      case "duplicate_alias"                            => "42712"
      case "duplicate_object"                           => "42710"
      case "ambiguous_column"                           => "42702"
      case "ambiguous_function"                         => "42725"
      case "ambiguous_parameter"                        => "42P08"
      case "ambiguous_alias"                            => "42P09"
      case "invalid_column_reference"                   => "42P10"
      case "invalid_column_definition"                  => "42611"
      case "invalid_cursor_definition"                  => "42P11"
      case "invalid_database_definition"                => "42P12"
      case "invalid_function_definition"                => "42P13"
      case "invalid_prepared_statement_definition"      => "42P14"
      case "invalid_schema_definition"                  => "42P15"
      case "invalid_table_definition"                   => "42P16"
      case "invalid_object_definition"                  => "42P17"
      case "with_check_option_violation"                => "44000"
      case "insufficient_resources"                     => "53000"
      case "disk_full"                                  => "53100"
      case "out_of_memory"                              => "53200"
      case "too_many_connections"                       => "53300"
      case "configuration_limit_exceeded"               => "53400"
      case "program_limit_exceeded"                     => "54000"
      case "statement_too_complex"                      => "54001"
      case "too_many_columns"                           => "54011"
      case "too_many_arguments"                         => "54023"
      case "object_not_in_prerequisite_state"           => "55000"
      case "object_in_use"                              => "55006"
      case "cant_change_runtime_param"                  => "55P02"
      case "lock_not_available"                         => "55P03"
      case "unsafe_new_enum_value_usage"                => "55P04"
      case "operator_intervention"                      => "57000"
      case "query_canceled"                             => "57014"
      case "admin_shutdown"                             => "57P01"
      case "crash_shutdown"                             => "57P02"
      case "cannot_connect_now"                         => "57P03"
      case "database_dropped"                           => "57P04"
      case "idle_session_timeout"                       => "57P05"
      case "system_error"                               => "58000"
      case "io_error"                                   => "58030"
      case "undefined_file"                             => "58P01"
      case "duplicate_file"                             => "58P02"
      case "snapshot_too_old"                           => "72000"
      case "config_file_error"                          => "F0000"
      case "lock_file_exists"                           => "F0001"
      case "fdw_error"                                  => "HV000"
      case "fdw_column_name_not_found"                  => "HV005"
      case "fdw_dynamic_parameter_value_needed"         => "HV002"
      case "fdw_function_sequence_error"                => "HV010"
      case "fdw_inconsistent_descriptor_information"    => "HV021"
      case "fdw_invalid_attribute_value"                => "HV024"
      case "fdw_invalid_column_name"                    => "HV007"
      case "fdw_invalid_column_number"                  => "HV008"
      case "fdw_invalid_data_type"                      => "HV004"
      case "fdw_invalid_data_type_descriptors"          => "HV006"
      case "fdw_invalid_descriptor_field_identifier"    => "HV091"
      case "fdw_invalid_handle"                         => "HV00B"
      case "fdw_invalid_option_index"                   => "HV00C"
      case "fdw_invalid_option_name"                    => "HV00D"
      case "fdw_invalid_string_length_or_buffer_length" => "HV090"
      case "fdw_invalid_string_format"                  => "HV00A"
      case "fdw_invalid_use_of_null_pointer"            => "HV009"
      case "fdw_too_many_handles"                       => "HV014"
      case "fdw_out_of_memory"                          => "HV001"
      case "fdw_no_schemas"                             => "HV00P"
      case "fdw_option_name_not_found"                  => "HV00J"
      case "fdw_reply_handle"                           => "HV00K"
      case "fdw_schema_not_found"                       => "HV00Q"
      case "fdw_table_not_found"                        => "HV00R"
      case "fdw_unable_to_create_execution"             => "HV00L"
      case "fdw_unable_to_create_reply"                 => "HV00M"
      case "fdw_unable_to_establish_connection"         => "HV00N"
      case "plpgsql_error"                              => "P0000"
      case "raise_exception"                            => "P0001"
      case "no_data_found"                              => "P0002"
      case "too_many_rows"                              => "P0003"
      case "assert_failure"                             => "P0004"
      case "internal_error"                             => "XX000"
      case "data_corrupted"                             => "XX001"
      case "index_corrupted"                            => "XX002"

  end inlineCode
end SQLSTATE
