name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

env:
  PG_VERSION: REL_12_7
  SBTN: 'sbt --client'

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: sbt

      # - name: Cache vcpkg
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/Library/Caches/sbt-vcpkg/vcpkg
      #       ~/.cache/sbt-vcpkg/vcpkg
      #       ~/.cache/sbt-vcpkg/vcpkg-install
      #     key: ${{ runner.os }}-sbt-vcpkg

      - name: Setup for Scala Native
        run: |
          echo "It's a Linux"
          sudo apt update
          sudo apt install lsb-release wget software-properties-common
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/focal/     llvm-toolchain-focal-13   main"
          sudo apt-get update 
          sudo apt-get install clang-13 lldb-13 libclang-13-dev llvm-13-dev

      - name: whaaat
        run: |
          $SBTN vcpkgInstall 
          ls -R $VCPKG_ROOT/packages
          ls -R ~/.cache/sbt-vcpkg/vcpkg-install/x64-linux/

      - name: Setup Postgres
        run: |
          set -e
          docker run -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres

      - name: CI 
        run: $SBTN 'test; publishLocal'

      - name: Publish ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

