name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

env:
  PG_VERSION: REL_12_7
  SBTN: 'sbt --client'

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'
          cache: sbt

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg-install
            ~/.cache/sbt-vcpkg/vcpkg
          key: ${{ runner.os }}-sbt-vcpkg

      - uses: rui314/setup-mold@v1

      - name: Setup Postgres
        run: |
          set -e
          docker run -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres

      - name: Tests 
        run: sbt test 

      - name: Docs 
        run: sbt 'docs/mdoc --in README.md'

      - name: Publish ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  mergify-build-checkpoint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"
