name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: coursier/cache-action@v6      

      - run: git fetch --unsallow

      - name: Setup for Scala Native
        run: |
          echo "It's a Linux"
          sudo apt update
          sudo apt install lsb-release wget software-properties-common
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/focal/     llvm-toolchain-focal-13   main"
          sudo apt-get update 
          sudo apt-get install clang-13 lldb-13 libclang-13-dev llvm-13-dev

      - name: Setup for examples
        run: |
          git submodule update --init

          BASE=$PWD

          cd postgres && ./configure

      - name: CI 
        run: sbt test publishLocal

      - name: Publish ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

